<?php 
/**
 * Gerencianet
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Payment
 * @package    Gerencianet_Transparent
 * @copyright  Copyright (c) 2015 Gerencianet (http://www.gerencianet.com.br)
 * @author     AV5 Tecnologia <anderson@av5.com.br>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $additionaldata = unserialize($this->getInfo()->getData('additional_data')); ?>
<p>Nro. Transa&ccedil;&atilde;o: <?php echo $this->getInfo()->getGerencianetChargeId(); ?></p>
<p>Data de Vencimento: <?php echo date('d/m/Y',strtotime($additionaldata['billet']['expires'])); ?></p>
<?php if (isset($additionaldata['billet']['link'])): ?>
<p><a href="<?php echo $additionaldata['billet']['link']; ?>">Imprimir Boleto</a></p>
<?php endif; ?>