<?php
/**
 * Gerencianet
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Payment
 * @package    Gerencianet_Transparent
 * @copyright  Copyright (c) 2015 Gerencianet (http://www.gerencianet.com.br)
 * @author     AV5 Tecnologia <anderson@av5.com.br>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_code = $this->getMethodCode();
$isSandbox = Mage::helper('gerencianet_transparent')->isSandbox();
?>

<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;"><!-- v0.1.9 -->

	<?php if ($isSandbox):	?>
	<div class="alert-development">
		<strong>ATEN&Ccedil;&Atilde;O!</strong>
		<p>Essa loja est&aacute; em Modo Desenvolvimento. O pagamento de cart&atilde;o de cr&eacute;dito ser&aacute; confirmado automaticamente no ambiente de Sandbox da Gerencianet.</p>
	</div>
	<?php endif; ?>

    <div class="pay-juridical-person">
		<p><input type="checkbox" onchange="GerencianetTransparent.payCardAsJuridical(this)" id="<?php echo $_code ?>_data_pay_card_as_juridical" name="payment[data_pay_card_as_juridical]" value="1" <?php if ($this->customer_cc_data_juridical) { echo 'checked'; } ?> /> Pagar como Pessoa Jurídica.</p>
		<div id="<?php echo $_code ?>_cc_juridical_data" <?php if (!$this->customer_cc_data_juridical) { echo 'class="gn-hide"'; } ?>>

		<li>
		<label for="<?php echo $_code ?>_cc_data_cnpj" class="required"><em>*</em><?php echo $this->__('CNPJ') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_cnpj" name="payment[cc_data_cnpj]" title="<?php echo $this->__('CNPJ') ?>" class="input-text validate-length" value="<?php if ($this->customer_cc_data_juridical) { echo $this->customer_cc_data_document; } ?>" />
		</div>
		</li>
		
		<li>
		<label for="<?php echo $_code ?>_cc_data_corporate_name" class="required"><em>*</em><?php echo $this->__('Razão Social') ?></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_cc_data_corporate_name" name="payment[cc_data_corporate_name]" title="<?php echo $this->__('Razão Social') ?>" class="input-text" value="<?php if ($this->customer_cc_data_juridical) { if ($this->customer_cc_data_razao_social) { echo $this->customer_cc_data_razao_social; } else {echo $this->customer_cc_data_name; } } ?>" maxlength="255" />
			</div>
		</div>
		</li>
	</div>

	<li <?php if (trim($this->customer_cc_data_name) != "" && !$this->customer_cc_data_juridical) { echo ' class="gn-hide"';} ?> >
		<label for="<?php echo  $_code ?>_cc_data_name" class="required"><em>*</em><?php echo $this->__('Nome') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_name" name="payment[cc_data_name]" title="<?php echo $this->__('Name') ?>" class="input-text " value="<?php if (!$this->customer_cc_data_juridical) { echo $this->customer_cc_data_name; } ?>" maxlength="255" />
		</div>
	</li>
    <li id="gerencianet_cc_cpf_row" <?php if (trim($this->customer_cc_data_document) != "" && !$this->customer_cc_data_juridical) { echo ' class="gn-hide"';} ?> >
		<label for="<?php echo $_code ?>_cc_data_cpf" class="required"><em>*</em><?php echo $this->__('CPF') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_cpf" name="payment[cc_data_cpf]" class="input-text " title="<?php echo $this->__('CPF') ?>" value="<?php if (!$this->customer_cc_data_juridical) { echo $this->customer_cc_data_document; } ?>" />
		</div>
	</li>
    <li id="gerencianet_cc_email_row" <?php if (trim($this->customer_cc_data_email) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_email" name="payment[cc_data_email]" class="input-text " title="<?php echo $this->__('E-mail') ?>" value="<?php echo $this->customer_cc_data_email; ?>" maxlength="255" />
		</div>
	</li>
	<li <?php if (trim($this->customer_cc_data_birth) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_birth" class="required"><em>*</em><?php echo $this->__('Data de Nascimento (DD/MM/AAAA)') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_birth" name="payment[cc_data_birth]" class="input-text validate-date-au " title="<?php echo $this->__('Data de Nascimento') ?>" value="<?php echo $this->customer_cc_data_birth; ?>" />
		</div>
	</li>
    <li <?php if (trim($this->customer_cc_data_phone_number) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_phone_number" class="required"><em>*</em><?php echo $this->__('Telefone (XX)XXXX-XXXX') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_phone_number" name="payment[cc_data_phone_number]" class="input-text " title="<?php echo $this->__('Phone Number') ?>" value="<?php echo $this->customer_cc_data_phone_number; ?>" />
		</div>
	</li>

	<li <?php if (trim($this->billing_cc_data_street) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo  $_code ?>_cc_data_street" class="required"><em>*</em><?php echo $this->__('Endereço de Cobrança') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_street" name="payment[cc_data_street]" title="<?php echo $this->__('Endereço') ?>" class="input-text " value="<?php echo $this->billing_cc_data_street; ?>" maxlength="255" />
		</div>
	</li>
    <li <?php if (trim($this->billing_cc_data_number) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_number" class="required"><em>*</em><?php echo $this->__('Número do endereço de cobrança') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_number" name="payment[cc_data_number]" class="input-text " title="<?php echo $this->__('Número') ?>" value="<?php echo $this->billing_cc_data_number; ?>" maxlength="11" />
		</div>
	</li>
    <li <?php if (trim($this->billing_cc_data_zipcode) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_zipcode" class="required"><em>*</em><?php echo $this->__('CEP do endereço de cobrança') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_zipcode" name="payment[cc_data_zipcode]" class="input-text " title="<?php echo $this->__('CEP') ?>" value="<?php echo $this->billing_cc_data_zipcode; ?>" maxlength="255" />
		</div>
	</li>
	<li <?php if (trim($this->billing_cc_data_neighborhood) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_neighborhood" class="required"><em>*</em><?php echo $this->__('Bairro do endereço de cobrança') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_neighborhood" name="payment[cc_data_neighborhood]" class="input-text " title="<?php echo $this->__('Bairro') ?>" value="<?php echo $this->billing_cc_data_neighborhood; ?>" maxlength="255" />
		</div>
	</li>
    <li <?php if (
    	trim($this->billing_cc_data_state) == "AC" ||
    	trim($this->billing_cc_data_state) == "AL" ||
    	trim($this->billing_cc_data_state) == "AP" ||
    	trim($this->billing_cc_data_state) == "AM" ||
    	trim($this->billing_cc_data_state) == "BA" ||
    	trim($this->billing_cc_data_state) == "CE" ||
    	trim($this->billing_cc_data_state) == "DF" ||
    	trim($this->billing_cc_data_state) == "ES" ||
    	trim($this->billing_cc_data_state) == "GO" ||
    	trim($this->billing_cc_data_state) == "MA" ||
    	trim($this->billing_cc_data_state) == "MT" ||
    	trim($this->billing_cc_data_state) == "MS" ||
    	trim($this->billing_cc_data_state) == "MG" ||
    	trim($this->billing_cc_data_state) == "PA" ||
    	trim($this->billing_cc_data_state) == "PB" ||
    	trim($this->billing_cc_data_state) == "PR" ||
    	trim($this->billing_cc_data_state) == "PE" ||
    	trim($this->billing_cc_data_state) == "PI" ||
    	trim($this->billing_cc_data_state) == "RJ" ||
    	trim($this->billing_cc_data_state) == "RN" ||
    	trim($this->billing_cc_data_state) == "RS" ||
    	trim($this->billing_cc_data_state) == "RO" ||
    	trim($this->billing_cc_data_state) == "RR" ||
    	trim($this->billing_cc_data_state) == "SC" ||
    	trim($this->billing_cc_data_state) == "SP" ||
    	trim($this->billing_cc_data_state) == "SE" ||
    	trim($this->billing_cc_data_state) == "TO"
	) { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_state" class="required"><em>*</em><?php echo $this->__('Estado') ?></label>
		<div class="input-box">
			<select id="<?php echo $_code ?>_cc_data_state" name="payment[cc_data_state]" class="input-select validate-select " >
                <option value="<?php echo $this->billing_cc_data_state; ?>">Selecione o Estado</option> 
                <option value="AC" <?php if (trim($this->billing_cc_data_state) == "AC") { echo " selected "; } ?>>Acre</option> 
                <option value="AL" <?php if (trim($this->billing_cc_data_state) == "AL") { echo " selected "; } ?>>Alagoas</option> 
                <option value="AP" <?php if (trim($this->billing_cc_data_state) == "AP") { echo " selected "; } ?>>Amapá</option> 
                <option value="AM" <?php if (trim($this->billing_cc_data_state) == "AM") { echo " selected "; } ?>>Amazonas</option> 
                <option value="BA" <?php if (trim($this->billing_cc_data_state) == "BA") { echo " selected "; } ?>>Bahia</option> 
                <option value="CE" <?php if (trim($this->billing_cc_data_state) == "CE") { echo " selected "; } ?>>Ceará</option> 
                <option value="DF" <?php if (trim($this->billing_cc_data_state) == "DF") { echo " selected "; } ?>>Distrito Federal</option> 
                <option value="ES" <?php if (trim($this->billing_cc_data_state) == "ES") { echo " selected "; } ?>>Espírito Santo</option> 
                <option value="GO" <?php if (trim($this->billing_cc_data_state) == "GO") { echo " selected "; } ?>>Goiás</option> 
                <option value="MA" <?php if (trim($this->billing_cc_data_state) == "MA") { echo " selected "; } ?>>Maranhão</option> 
                <option value="MT" <?php if (trim($this->billing_cc_data_state) == "MT") { echo " selected "; } ?>>Mato Grosso</option> 
                <option value="MS" <?php if (trim($this->billing_cc_data_state) == "MS") { echo " selected "; } ?>>Mato Grosso do Sul</option> 
                <option value="MG" <?php if (trim($this->billing_cc_data_state) == "MG") { echo " selected "; } ?>>Minas Gerais</option> 
                <option value="PA" <?php if (trim($this->billing_cc_data_state) == "PA") { echo " selected "; } ?>>Pará</option> 
                <option value="PB" <?php if (trim($this->billing_cc_data_state) == "PB") { echo " selected "; } ?>>Paraíba</option> 
                <option value="PR" <?php if (trim($this->billing_cc_data_state) == "PR") { echo " selected "; } ?>>Paraná</option> 
                <option value="PE" <?php if (trim($this->billing_cc_data_state) == "PE") { echo " selected "; } ?>>Pernambuco</option> 
                <option value="PI" <?php if (trim($this->billing_cc_data_state) == "PI") { echo " selected "; } ?>>Piauí</option> 
                <option value="RJ" <?php if (trim($this->billing_cc_data_state) == "RJ") { echo " selected "; } ?>>Rio de Janeiro</option> 
                <option value="RN" <?php if (trim($this->billing_cc_data_state) == "RN") { echo " selected "; } ?>>Rio Grande do Norte</option> 
                <option value="RS" <?php if (trim($this->billing_cc_data_state) == "RS") { echo " selected "; } ?>>Rio Grande do Sul</option> 
                <option value="RO" <?php if (trim($this->billing_cc_data_state) == "RO") { echo " selected "; } ?>>Rondônia</option> 
                <option value="RR" <?php if (trim($this->billing_cc_data_state) == "RR") { echo " selected "; } ?>>Roraima</option> 
                <option value="SC" <?php if (trim($this->billing_cc_data_state) == "SC") { echo " selected "; } ?>>Santa Catarina</option> 
                <option value="SP" <?php if (trim($this->billing_cc_data_state) == "SP") { echo " selected "; } ?>>São Paulo</option> 
                <option value="SE" <?php if (trim($this->billing_cc_data_state) == "SE") { echo " selected "; } ?>>Sergipe</option> 
                <option value="TO" <?php if (trim($this->billing_cc_data_state) == "TO") { echo " selected "; } ?>>Tocantins</option> 
            </select>
		</div>
	</li>
	<li <?php if (trim($this->billing_cc_data_city) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_cc_data_city" class="required"><em>*</em><?php echo $this->__('Cidade') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_city" name="payment[cc_data_city]" class="input-text " title="<?php echo $this->__('Cidade') ?>" value="<?php echo $this->billing_cc_data_city; ?>" maxlength="255" />
		</div>
	</li>
    <li class="gn-hide">
		<label for="<?php echo $_code ?>_cc_data_complement" class="required"><em>*</em><?php echo $this->__('Complemento') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_data_complement" name="payment[cc_data_complement]" class="input-text" title="<?php echo $this->__('Complemento') ?>" value="<?php echo $this->billing_cc_data_complement; ?>" maxlength="55" />
		</div>
	</li>

	<li class="first">
		<?php $_ccType = $this->getInfoData('cc_type') ?>
		<ul class="card-logo">
		<?php foreach ($this->getCcAvailableTypes() as $_typeCode => $_typeName): ?>
			<li>

				<label class="brand-label" title="<?php echo $_typeName ?>">
					<input name="payment[cc_type]" type="radio" value="<?php echo $_typeCode ?>" id="<?php echo $_code ?>_cc_type" class="validate-one-required-by-name" onclick="javascript: GerencianetTransparent.calculateInstallments();" />
					<img src="<?php echo $this->getSkinUrl('images/gerencianet/'.$_typeCode.'.png') ?>" />
				</label>
			</li>
		<?php endforeach ?>
		</ul>
	</li>
	<li>
		<label for="<?php echo $_code ?>_cc_owner" class="required"><em>*</em><?php echo $this->__('Name on Card') ?></label>
		<div class="input-box">
			<input type="text" title="<?php echo $this->__('Name on Card') ?>" class="input-text " id="<?php echo $_code ?>_cc_owner" name="payment[cc_owner]" value="<?php echo $this->htmlEscape($this->getInfoData('cc_owner')) ?>" onchange="javascript: GerencianetTransparent.cardPaymentValidate();" />
		</div>
	</li>
	<li>
		<label for="<?php echo $_code ?>_cc_number" class="required"><em>*</em><?php echo $this->__('Credit Card Number') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_cc_number" name="payment[cc_number]" title="<?php echo $this->__('Credit Card Number') ?>" class="input-text " value="" maxlength="16" onchange="javascript: GerencianetTransparent.cardPaymentValidate();" />
		</div>
	</li>
	<li id="<?php echo $_code ?>_cc_type_exp_div">
		<label for="<?php echo $_code ?>_expiration" class="required"><em>*</em><?php echo $this->__('Expiration Date') ?></label>
		<div class="input-box">
			<div class="v-fix">
				<select id="<?php echo $_code ?>_cc_expiration" name="payment[cc_exp_month]" class="month validate-cc-exp " onchange="javascript: GerencianetTransparent.cardPaymentValidate();">
				<?php $_ccExpMonth = $this->getInfoData('cc_exp_month') ?>
				<?php foreach ($this->getCcMonths() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpMonth): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</div>
			<div class="v-fix">
				<select id="<?php echo $_code ?>_cc_expiration_yr" name="payment[cc_exp_year]" class="year " onchange="javascript: GerencianetTransparent.cardPaymentValidate();">
				<?php $_ccExpYear = $this->getInfoData('cc_exp_year') ?>
				<?php foreach ($this->getCcYears() as $k=>$v): ?>
					<option value="<?php echo $k?$k:'' ?>"<?php if($k==$_ccExpYear): ?> selected="selected"<?php endif ?>><?php echo $v ?></option>
				<?php endforeach ?>
				</select>
			</div>
		</div>
	</li>
	<?php echo $this->getChildHtml() ?>
	<?php if($this->hasVerification()): ?>
	<li>
		<label for="<?php echo $_code ?>_cc_cid" class="required"><em>*</em><?php echo $this->__('Card Verification Number') ?></label>
		<div class="input-box">
			<div class="v-fix">
				<input type="text" title="<?php echo $this->__('Card Verification Number') ?>" class="input-text cvv validate-digits " size="5" id="<?php echo $_code ?>_cc_cid" name="payment[cc_cid]" value="" maxlength="4" onchange="javascript: GerencianetTransparent.cardPaymentValidate();" />
			</div>
			<a href="#" class="cvv-what-is-this"><?php echo $this->__('What is this?') ?></a>
		</div>
	</li>
	<?php endif; ?>
	<li>
		<label for="<?php echo $_code ?>_installments"><?php echo $this->__('Parcelas') ?> </label>
		<div class="input-box" id="installments">
			<select id="<?php echo $_code ?>_cc_installments" name="payment[cc_installments]">
			</select>
		</div>
	</li>
	<input type="hidden" id="<?php echo $_code; ?>_token" name="payment[cc_token]" value="" class="validate-payment-token" />
</ul>


<script type="text/javascript">
//< ![CDATA[
var customForm = new VarienForm('form-list');
Validation.defaultOptions.immediate = true;
//]]>
</script>

<style type="text/css">
.gn-hide { display: none; }
.pay-juridical-person { color: #707070; border: 1px solid #CCC; margin-top: 20px; margin-bottom: 20px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.pay-juridical-person p { color: #707070; margin: 0; padding: 0; font-size: 13px; }
.alert-development { color: #c90000; border: 1px solid #c90000; margin-top: 20px; margin-bottom: 20px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.alert-development p { color: #707070; margin: 0; padding: 0; font-size: 13px; }
.card-logo input { position: absolute; top: 15px; left: 4px; }
.brand-label { border: 1px solid #ddd; padding: 5px 5px 5px 20px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; cursor: pointer; position: relative; }

.card-logo { display: inline-block; }
.card-logo li { float: left; text-align: center; margin-right: 10px !important;height:57px;vertical-align:bottom;display:block; position:relative; }
.card-logo li .validation-advice {position:absolute;top:55px;width:150px; }
.card-logo li label img { display: block; }

.sp-methods .form-list li .input-box .input-text.cvv { width:50px; margin-right:5px; }
.form-list li.first { text-align: center; }
.sp-methods .form-list li label,
.sp-methods .form-list li .input-box { width:300px; margin-right: 0px;}
.form-list .card-logo li label,
.sp-methods .form-list li .input-box select { width:auto !important;margin-right:5px; text-align: center;}
</style>


<script type="text/javascript"> 

//<![CDATA[
if (jQuery!=undefined) 
    jQuery(document).ready(function(e){  

		<?php if ($this->customer_cc_data_juridical && $this->customer_cc_data_document!="") { ?>
			jQuery('#gerencianet_card_cc_juridical_data').removeClass("gn-hide");
			jQuery('#gerencianet_card_data_pay_card_as_juridical').prop( "checked", true );
		<?php } else { ?>
			jQuery('#gerencianet_card_cc_juridical_data').addClass("gn-hide");
			jQuery('#gerencianet_card_data_pay_card_as_juridical').prop( "checked", false );
		<?php } ?>

    	if (jQuery("#gerencianet_card_cc_data_email").val()=="") {
    		if (jQuery("[name='billing[email]']")) {
	    		jQuery("#gerencianet_card_cc_data_email").val(jQuery("[name='billing[email]']").val());
	    	}
    	}

		if (jQuery("[name='billing[taxvat]']").val()!="") {
			if (jQuery("#gerencianet_card_cc_data_cpf").val()=="" && verifyCPF(jQuery("[name='billing[taxvat]']").val())) {
	    		jQuery("#gerencianet_card_cc_data_cpf").val(jQuery("[name='billing[taxvat]']").val());
	    		if (jQuery("#gerencianet_card_cc_data_name").val()=="") {
		    		jQuery("#gerencianet_card_cc_data_name").val(jQuery("[name='billing[firstname]']").val() + " " + jQuery("[name='billing[lastname]']").val());
		    	}
	    	} else if (jQuery("#gerencianet_card_cc_data_cnpj").val()=="" && verifyCNPJ(jQuery("[name='billing[taxvat]']").val())) {
	    		jQuery("#gerencianet_card_cc_data_cnpj").val(jQuery("[name='billing[taxvat]']").val());
	    		jQuery('#gerencianet_card_cc_juridical_data').removeClass("gn-hide");
				jQuery('#gerencianet_card_data_pay_card_as_juridical').prop( "checked", true );
		    	if (jQuery("#gerencianet_card_cc_data_corporate_name").val()=="" && jQuery("[name='billing[razao_social]']")) {
		    		jQuery("#gerencianet_card_cc_data_corporate_name").val(jQuery("[name='billing[razao_social]']").val());
		    	} else if (jQuery("#gerencianet_card_cc_data_corporate_name").val()=="") {
		    		jQuery("#gerencianet_card_cc_data_corporate_name").val(jQuery("[name='billing[firstname]']").val() + " " + jQuery("[name='billing[lastname]']").val());
		    	}
	    	}
    	}
    	
    	if (jQuery.mask) {
	    	jQuery("#gerencianet_card_cc_data_cpf").mask("999.999.999-99",{
	    		completed:function(){ 
	    			if (!verifyCPF(this.val())) {
	    				this.addClass( "validation-failed" );
	    				alert("CPF inválido.");
	    			} else {
	    				this.removeClass( "validation-failed" );
	    			}
	    		},placeholder:"___.___.___-__"});

	    	jQuery("#gerencianet_card_cc_data_cnpj").mask("99.999.999/9999-99",{
	    		completed:function(){ 
	    			if (!verifyCNPJ(this.val())) {
	    				this.addClass( "validation-failed" );
	    				alert("CNPJ inválido.");
	    			} else {
	    				this.removeClass( "validation-failed" );
	    			}
	    		},placeholder:"__.___.___/____-__"});

	    	jQuery("#gerencianet_card_cc_data_birth").mask("99/99/9999",{
	    		completed:function(){ 
	    			if (!verifyBirthdate(this.val())) {
	    				this.addClass( "validation-failed" );
	    				alert("Data de nascimento inválida.");
	    			} else {
	    				this.removeClass( "validation-failed" );
	    			}
	    		},placeholder:"__/__/____"});

			jQuery("#gerencianet_card_cc_data_phone_number").focusout(function(){
			jQuery("#gerencianet_card_cc_data_phone_number").unmask();
				var phone = jQuery("#gerencianet_card_cc_data_phone_number").val().replace(/[^\d]+/g,'');
				if(phone.length > 10) {
					jQuery("#gerencianet_card_cc_data_phone_number").mask("(99) 99999-999?9");
				} else {
					jQuery("#gerencianet_card_cc_data_phone_number").mask("(99) 9999-9999?9");
				}
			}).trigger("focusout");
		}

		if (verifyCPF(jQuery("#gerencianet_card_cc_data_cpf").val())) {
			jQuery('#gerencianet_cc_cpf_row').addClass("gn-hide");
		} else {
			jQuery('#gerencianet_cc_cpf_row').removeClass("gn-hide");
		}

		if (verifyEmail(jQuery("#gerencianet_card_cc_data_email").val())) {
			jQuery('#gerencianet_cc_email_row').addClass("gn-hide");
		} else {
			jQuery('#gerencianet_cc_email_row').removeClass("gn-hide");
		}
    
    });
	
	function verifyEmail(email) {
    	var pattern = /^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/;
        return pattern.test(email);
    }
	
	function verifyCPF(cpf) {
		if (cpf!=undefined) {
	        cpf = cpf.replace(/[^\d]+/g,'');
	        
	        if(cpf == '' || cpf.length != 11) return false;
	        
	        var resto;
	        var soma = 0;
	        
	        if (cpf == "00000000000" || cpf == "11111111111" || cpf == "22222222222" || cpf == "33333333333" || cpf == "44444444444" || cpf == "55555555555" || cpf == "66666666666" || cpf == "77777777777" || cpf == "88888888888" || cpf == "99999999999" || cpf == "12345678909") return false;
	        
	        for (i=1; i<=9; i++) soma = soma + parseInt(cpf.substring(i-1, i)) * (11 - i);
	        resto = (soma * 10) % 11;
	        
	        if ((resto == 10) || (resto == 11))  resto = 0;
	        if (resto != parseInt(cpf.substring(9, 10)) ) return false;
	        
	        soma = 0;
	        for (i = 1; i <= 10; i++) soma = soma + parseInt(cpf.substring(i-1, i)) * (12 - i);
	        resto = (soma * 10) % 11;
	        
	        if ((resto == 10) || (resto == 11))  resto = 0;
	        if (resto != parseInt(cpf.substring(10, 11) ) ) return false;
	        return true;
	    } else {
	    	return false;
	    }
    }

    function verifyCNPJ(cnpj) {
    	if (cnpj!=undefined) {
	        cnpj = cnpj.replace(/[^\d]+/g,'');

	        if(cnpj == '' || cnpj.length != 14) return false;

	        if (cnpj == "00000000000000" || cnpj == "11111111111111" || cnpj == "22222222222222" || cnpj == "33333333333333" || cnpj == "44444444444444" || cnpj == "55555555555555" || cnpj == "66666666666666" || cnpj == "77777777777777" || cnpj == "88888888888888" || cnpj == "99999999999999") return false;

	        var tamanho = cnpj.length - 2
	        var numeros = cnpj.substring(0,tamanho);
	        var digitos = cnpj.substring(tamanho);
	        var soma = 0;
	        var pos = tamanho - 7;
	        
	        for (i = tamanho; i >= 1; i--) {
	          soma += numeros.charAt(tamanho - i) * pos--;
	          if (pos < 2)
	                pos = 9;
	        }
	        
	        var resultado = soma % 11 < 2 ? 0 : 11 - soma % 11;
	        
	        if (resultado != digitos.charAt(0)) return false;

	        tamanho = tamanho + 1;
	        numeros = cnpj.substring(0,tamanho);
	        soma = 0;
	        pos = tamanho - 7;
	        
	        for (i = tamanho; i >= 1; i--) {
	          soma += numeros.charAt(tamanho - i) * pos--;
	          if (pos < 2) pos = 9;
	        }
	        
	        resultado = soma % 11 < 2 ? 0 : 11 - soma % 11;
	        
	        if (resultado != digitos.charAt(1)) return false;

	        return true; 
        } else {
	    	return false;
	    }
    }

    function verifyBirthdate(birth) {
        var pattern = new RegExp(/^[12][0-9]{3}-(?:0[1-9]|1[0-2])-(?:0[1-9]|[12][0-9]|3[01])$/);
        var date = birth.split("/");
        return pattern.test(date[2] + "-" + date[1] + "-" + date[0]);
    }

//]]>

</script>

<script>
		if (document.getElementById('gerencianet_card_cc_data_cnpj')) {
			<?php if ($this->customer_cc_data_name!="" && $this->customer_cc_data_juridical) { ?>
				document.getElementById('gerencianet_card_cc_data_cnpj').value = "<?php echo $this->customer_cc_data_document; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_corporate_name')) {
			<?php if ($this->customer_cc_data_document!="" && $this->customer_cc_data_juridical) { ?>
				document.getElementById('gerencianet_card_cc_data_corporate_name').value = "<?php echo $this->customer_cc_data_name; ?>";
			<?php } ?>
		}

		if (document.getElementById('gerencianet_card_cc_data_name')) {
			<?php if ($this->customer_cc_data_name!="" && !$this->customer_cc_data_juridical) { ?>
				document.getElementById('gerencianet_card_cc_data_name').value = "<?php echo $this->customer_cc_data_name; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_cpf')) {
			<?php if ($this->customer_cc_data_document!="" && !$this->customer_cc_data_juridical) { ?>
				document.getElementById('gerencianet_card_cc_data_cpf').value = "<?php echo $this->customer_cc_data_document; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_email')) {
			<?php if ($this->customer_cc_data_email!="") { ?>
				document.getElementById('gerencianet_card_cc_data_email').value = "<?php echo $this->customer_cc_data_email; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_birth')) {
			<?php if ($this->customer_cc_data_birth!="") { ?>
				document.getElementById('gerencianet_card_cc_data_birth').value = "<?php echo $this->customer_cc_data_birth; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_phone_number')) {
			<?php if ($this->customer_cc_data_phone_number!="") { ?>
				document.getElementById('gerencianet_card_cc_data_phone_number').value = "<?php echo $this->customer_cc_data_phone_number; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_street')) {
			<?php if ($this->billing_cc_data_street!="") { ?>
				document.getElementById('gerencianet_card_cc_data_street').value = "<?php echo $this->billing_cc_data_street; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_number')) {
			<?php if ($this->billing_cc_data_number!="") { ?>
				document.getElementById('gerencianet_card_cc_data_number').value = "<?php echo $this->billing_cc_data_number; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_zipcode')) {
			<?php if ($this->billing_cc_data_zipcode!="") { ?>
				document.getElementById('gerencianet_card_cc_data_zipcode').value = "<?php echo $this->billing_cc_data_zipcode; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_neighborhood')) {
			<?php if ($this->billing_cc_data_neighborhood!="") { ?>
				document.getElementById('gerencianet_card_cc_data_neighborhood').value = "<?php echo $this->billing_cc_data_neighborhood; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_state')) {
			<?php if (
		    	trim($this->billing_cc_data_state) == "AC" ||
		    	trim($this->billing_cc_data_state) == "AL" ||
		    	trim($this->billing_cc_data_state) == "AP" ||
		    	trim($this->billing_cc_data_state) == "AM" ||
		    	trim($this->billing_cc_data_state) == "BA" ||
		    	trim($this->billing_cc_data_state) == "CE" ||
		    	trim($this->billing_cc_data_state) == "DF" ||
		    	trim($this->billing_cc_data_state) == "ES" ||
		    	trim($this->billing_cc_data_state) == "GO" ||
		    	trim($this->billing_cc_data_state) == "MA" ||
		    	trim($this->billing_cc_data_state) == "MT" ||
		    	trim($this->billing_cc_data_state) == "MS" ||
		    	trim($this->billing_cc_data_state) == "MG" ||
		    	trim($this->billing_cc_data_state) == "PA" ||
		    	trim($this->billing_cc_data_state) == "PB" ||
		    	trim($this->billing_cc_data_state) == "PR" ||
		    	trim($this->billing_cc_data_state) == "PE" ||
		    	trim($this->billing_cc_data_state) == "PI" ||
		    	trim($this->billing_cc_data_state) == "RJ" ||
		    	trim($this->billing_cc_data_state) == "RN" ||
		    	trim($this->billing_cc_data_state) == "RS" ||
		    	trim($this->billing_cc_data_state) == "RO" ||
		    	trim($this->billing_cc_data_state) == "RR" ||
		    	trim($this->billing_cc_data_state) == "SC" ||
		    	trim($this->billing_cc_data_state) == "SP" ||
		    	trim($this->billing_cc_data_state) == "SE" ||
		    	trim($this->billing_cc_data_state) == "TO") { ?>
				document.getElementById('gerencianet_card_cc_data_state').value = "<?php echo $this->billing_cc_data_state; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_city')) {
			<?php if ($this->billing_cc_data_city!="") { ?>
				document.getElementById('gerencianet_card_cc_data_city').value = "<?php echo $this->billing_cc_data_city; ?>";
			<?php } ?>
		}
		if (document.getElementById('gerencianet_card_cc_data_complement')) {
			<?php if ($this->billing_cc_data_complement!="") { ?>
				document.getElementById('gerencianet_card_cc_data_complement').value = "<?php echo $this->billing_cc_data_complement; ?>";
			<?php } ?>
		}
	
</script>
