<?php 
/**
 * Gerencianet
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Payment
 * @package    Gerencianet_Transparent
 * @copyright  Copyright (c) 2015 Gerencianet (http://www.gerencianet.com.br)
 * @author     AV5 Tecnologia <anderson@av5.com.br>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$additionaldata = unserialize($this->getInfo()->getData('additional_data'));
$additionaldata = $additionaldata['card'];
?>
<p><?php echo $this->__('Name on the Card: %s', $this->htmlEscape($this->getInfo()->getCcOwner())) ?></p>
<p><?php echo $this->__('Credit Card Type: %s', $this->htmlEscape($this->getCcTypeName())) ?></p>
<p><?php echo $this->__('Credit Card Number: xxxx-%s', $this->htmlEscape($this->getInfo()->getCcLast4())) ?></p>
<p><?php echo $this->__('Expiration Date: %s/%s', $this->htmlEscape($this->getInfo()->getCcExpMonth()), $this->htmlEscape($this->getInfo()->getCcExpYear())) ?></p>
<p><?php echo $this->__('Número de Parcelas: %s', $additionaldata["cc_installments"]) ?></p>
<?php if(isset($additionaldata["tid"])): ?>
	<?php if($additionaldata["tid"]): ?>
	<p><?php echo $this->__('Código da transação: %s', $additionaldata["tid"]) ?></p>
	<?php endif ?>
	<?php if(isset($additionaldata["erro"])): ?>
	<p><?php echo $this->__('Mensagem da transação: (%s) %s', $additionaldata["erro"]['codigo'], $additionaldata["erro"]['mensagem']) ?></p>
	<?php elseif(isset($additionaldata["autorizacao"])): ?>
	<p><?php echo $this->__('Mensagem da transação: (%s) %s', $additionaldata["autorizacao"]['codigo'], $additionaldata["autorizacao"]['mensagem']) ?></p>
	<?php endif ?>
<?php endif ?>
