<?php
/**
 * Gerencianet
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Payment
 * @package    Gerencianet_Transparent
 * @copyright  Copyright (c) 2016 Gerencianet (http://www.gerencianet.com.br)
 * @author     Gerencianet
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_code = $this->getMethodCode();
$isSandbox = Mage::helper('gerencianet_transparent')->isSandbox();
?>
<!-- v0.2.1 -->
<div class="gn-osc-payment-box">
	<ul class="form-list billet-payment" id="payment_form_<?php echo $_code ?>" style="display:none;">
		<?php if ($this->order_total<5):	?>
		<div class="alert-development">
			<strong>ATENÇÃO!</strong>
			<p>O valor mínimo para pagar com a Gerencianet é R$5,00.</p>
		</div>
		<div style="display: none;">
		<?php endif; ?>
		<div class="gn-osc-billet-info">
		<?php if ($isSandbox):	?>
		<div class="alert-development">
			<strong>ATENÇÃO!</strong>
			<p>Essa loja está em Modo Desenvolvimento. Um boleto de teste será gerado no ambiente de Sandbox da Gerencianet.</p>
		</div>
		<?php endif; ?>

	    <div class="pay-juridical-person-billet">
			<p><input type="checkbox" onchange="GerencianetBilletTransparent.payBilletAsJuridical(this)" id="<?php echo $_code ?>_data_pay_billet_as_juridical" name="payment[data_pay_billet_as_juridical]" value="1" <?php if ($this->customer_data_juridical) { echo 'checked'; } ?> /> Pagar como Pessoa Jurídica.</p>
			<div id="<?php echo $_code ?>_juridical_data" <?php if (!$this->customer_data_juridical) { echo 'class="gn-hide"'; } ?>>

			<li>
			<label for="<?php echo $_code ?>_data_cnpj" class="required"><?php echo $this->__('CNPJ') ?></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_data_cnpj" name="payment[data_cnpj]" title="<?php echo $this->__('CNPJ') ?>" class="input-text validate-length" value="<?php if ($this->customer_data_juridical) { echo $this->customer_data_document; } ?>" />
			</div>
			</li>

			<li>
			<label for="<?php echo $_code ?>_data_corporate_name" class="required"><?php echo $this->__('Razão Social') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_data_corporate_name" name="payment[data_corporate_name]" title="<?php echo $this->__('Razão Social') ?>" class="input-text" value="<?php if ($this->customer_data_juridical) { if ($this->customer_data_razao_social) { echo $this->customer_data_razao_social; } else {echo $this->customer_data_name; } } ?>" maxlength="255" />
				</div>
			</li>
			</div>
		</div>

	    <li id="gerencianet_billet_name_row">
	    	<div class="gn-osc-field-row">
				<label for="<?php echo $_code ?>_data_name" class="required"><?php echo $this->__('NOME') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_data_name" name="payment[data_name]" title="<?php echo $this->__('Name') ?>" class="input-text required-entry" value="<?php if (!$this->customer_data_juridical) { echo $this->customer_data_name; } ?>" maxlength="255" />
				</div>
			</div>
		</li>
	    <li id="gerencianet_billet_cpf_phone_row">
	    	<div class="gn-osc-field-row">
	    		<div class="gn-osc-clear">
					<div style="float: left; width: 48%;">
						<label for="<?php echo $_code ?>_data_cpf" class="required"><?php echo $this->__('CPF') ?></label>
						<div class="input-box">
							<input type="text" id="<?php echo $_code ?>_data_cpf" name="payment[data_cpf]" class="input-text required-entry" title="<?php echo $this->__('CPF') ?>" value="<?php if (!$this->customer_data_juridical) { echo $this->customer_data_document; } ?>" />
						</div>
					</div>
					<div style="float: right; width: 48%;">
						<label for="<?php echo $_code ?>_data_phone_number" class="required"><?php echo $this->__('TELEFONE') ?></label>
						<div class="input-box">
							<input type="text" id="<?php echo $_code ?>_data_phone_number" name="payment[data_phone_number]" class="input-text required-entry" title="<?php echo $this->__('Phone Number') ?>" value="<?php echo $this->customer_data_phone_number; ?>" />
						</div>
					</div>
				</div>
			</div>
		</li>
	    <li id="gerencianet_billet_email_row" <?php if (trim($this->customer_data_email) != "") { echo ' class="gn-hide"';} ?>>
			<div class="gn-osc-field-row">
				<label for="<?php echo $_code ?>_data_email" class="required"><?php echo $this->__('EMAIL') ?></label>
				<div class="input-box">
					<input type="text" id="<?php echo $_code ?>_data_email" name="payment[data_email]" class="input-text required-entry" title="<?php echo $this->__('E-mail') ?>" value="<?php echo $this->customer_data_email; ?>" maxlength="255" />
				</div>
			</div>
		</li>
		</div>
		<?php if ($this->order_total<5):	?> </div><?php endif; ?>
	</ul>
</div>
<style type="text/css">
.gn-osc-payment-box {
	margin: 3px;
	width: 100%;
}
.gn-osc-payment-box input[type=text], .gn-osc-payment-box select {
	width: 100%;
}
.gn-osc-billet-info {
	background-color: #FFF; 
	padding: 5px;
    border-radius: 4px;
    -webkit-border-radius: 4px;
    border-radius: 4px;
}

.gn-hide { display: none; }
.pay-juridical-person-billet { color: #707070; background-color: #F9F9F9; margin-top: 10px; margin-bottom: 10px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.pay-juridical-person-billet p { color: #707070; margin: 0; padding: 0; font-size: 13px; }
.alert-development { color: #8a6d3b; background-color: #fcf8e3; border: 1px solid #faebcc; margin-top: 10px; margin-bottom: 20px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; font-size: 12px; }
.alert-development p { color: #8a6d3b; margin: 0; padding: 0; font-size: 11px; }
.alert-development strong { color: #c90000; }
</style>

<script type="text/javascript"> 

var GerencianetBilletTransparent = function GerencianetBilletTransparent(){};

GerencianetBilletTransparent.payBilletAsJuridical = function(element) {
	if (element.checked) {
		document.getElementById('gerencianet_billet_juridical_data').style.display = 'block';
	} else {
		document.getElementById('gerencianet_billet_juridical_data').style.display = 'none';
	}
};

if (jQuery!=undefined) 

    jQuery(document).ready(function(e){  

    	<?php if ($this->customer_data_juridical && $this->customer_data_document!="") { ?>
			jQuery('#gerencianet_billet_juridical_data').removeClass("gn-hide");
			jQuery('#gerencianet_billet_data_pay_billet_as_juridical').prop( "checked", true );
		<?php } else { ?>
			jQuery('#gerencianet_billet_juridical_data').addClass("gn-hide");
			jQuery('#gerencianet_billet_data_pay_billet_as_juridical').prop( "checked", false );
		<?php } ?>

    	if (jQuery("#gerencianet_billet_data_email").val()=="") {
    		if (jQuery("[name='billing[email]']")) {
	    		jQuery("#gerencianet_billet_data_email").val(jQuery("[name='billing[email]']").val());
	    	}
    	}

		if (jQuery("[name='billing[taxvat]']").val()!="") {
			if (jQuery("#gerencianet_billet_data_cpf").val()=="" && verifyCPF(jQuery("[name='billing[taxvat]']").val())) {
	    		jQuery("#gerencianet_billet_data_cpf").val(jQuery("[name='billing[taxvat]']").val());
	    		if (jQuery("#gerencianet_billet_data_name").val()=="") {
		    		jQuery("#gerencianet_billet_data_name").val(jQuery("[name='billing[firstname]']").val() + " " + jQuery("[name='billing[lastname]']").val());
		    	}
	    	} else if (jQuery("#gerencianet_billet_data_cnpj").val()=="" && verifyCNPJ(jQuery("[name='billing[taxvat]']").val())) {
	    		jQuery("#gerencianet_billet_data_cnpj").val(jQuery("[name='billing[taxvat]']").val());
	    		jQuery('#gerencianet_billet_juridical_data').removeClass("gn-hide");
				jQuery('#gerencianet_billet_data_pay_billet_as_juridical').prop( "checked", true );
				if (jQuery("#gerencianet_billet_data_corporate_name").val()=="" && jQuery("[name='billing[razao_social]']")) {
		    		jQuery("#gerencianet_billet_data_corporate_name").val(jQuery("[name='billing[razao_social]']").val());
		    	} else if (jQuery("#gerencianet_billet_data_corporate_name").val()=="") {
		    		jQuery("#gerencianet_billet_data_corporate_name").val(jQuery("[name='billing[firstname]']").val() + " " + jQuery("[name='billing[lastname]']").val());
		    	}
	    	}
    	}
    	
    	if (jQuery.mask) {
	    	jQuery("#gerencianet_billet_data_cpf").mask("999.999.999-99",{
	    		completed:function(){ 
	    			if (!verifyCPF(this.val())) {
	    				this.addClass( "validation-failed" );
	    				alert("CPF inválido.");
	    			} else {
	    				this.removeClass( "validation-failed" );
	    			}
	    		},placeholder:"___.___.___-__"});

	    	jQuery("#gerencianet_billet_data_cnpj").mask("99.999.999/9999-99",{
	    		completed:function(){ 
	    			if (!verifyCNPJ(this.val())) {
	    				this.addClass( "validation-failed" );
	    				alert("CNPJ inválido.");
	    			} else {
	    				this.removeClass( "validation-failed" );
	    			}
	    		},placeholder:"__.___.___/____-__"});

			jQuery("#gerencianet_billet_data_phone_number").focusout(function(){
			jQuery("#gerencianet_billet_data_phone_number").unmask();
				var phone = jQuery("#gerencianet_billet_data_phone_number").val().replace(/[^\d]+/g,'');
				if(phone.length > 10) {
					jQuery("#gerencianet_billet_data_phone_number").mask("(99) 99999-999?9");
				} else {
					jQuery("#gerencianet_billet_data_phone_number").mask("(99) 9999-9999?9");
				}
			}).trigger("focusout");
		}

		if (validateEmail(jQuery("#gerencianet_billet_data_email").val())) {
			jQuery('#gerencianet_billet_email_row').addClass("gn-hide");
		} else {
			jQuery('#gerencianet_billet_email_row').removeClass("gn-hide");
		}

		if (verifyCPF(jQuery("#gerencianet_billet_data_cpf").val()) && validatePhone(jQuery('#gerencianet_billet_data_phone_number').val())) {
			jQuery('#gerencianet_billet_cpf_phone_row').addClass("gn-hide");
		} else {
			jQuery('#gerencianet_billet_cpf_phone_row').removeClass("gn-hide");
		}

		if (validateNameBillet(jQuery('#gerencianet_billet_data_name').val())) {
			jQuery('#gerencianet_billet_name_row').addClass("gn-hide");
		} else {
			jQuery('#gerencianet_billet_name_row').removeClass("gn-hide");
		}
    
    });

	function validateNameBillet(data) {
        if (data) {
            if (data.length > 7) {
                return true;
            } else {
                return false;
            }
        }
    }

    function validateEmail(email) {
        if (email) {
            var pattern = new RegExp(/^([a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+(\.[a-z\d!#$%&'*+\-\/=?^_`{|}~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]+)*|"((([ \t]*\r\n)?[ \t]+)?([\x01-\x08\x0b\x0c\x0e-\x1f\x7f\x21\x23-\x5b\x5d-\x7e\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|\\[\x01-\x09\x0b\x0c\x0d-\x7f\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]))*(([ \t]*\r\n)?[ \t]+)?")@(([a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\d\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.)+([a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]|[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF][a-z\d\-._~\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF]*[a-z\u00A0-\uD7FF\uF900-\uFDCF\uFDF0-\uFFEF])\.?$/);
            return pattern.test(email);
        } else {
            return false;
        }
    }

    function validatePhone(phone_number) {
        if (phone_number) {
            if (phone_number.replace(/[^\d]+/g,'').length < 10) {
                return false; 
            } else {
                var pattern = new RegExp(/^[1-9]{2}9?[0-9]{8}$/);
                if (pattern.test(phone_number.replace(/[^\d]+/g,''))) {
                    return true; 
                } else {
                    return false; 
                }
            }
        }
    }
	
	function verifyCPF(cpf) {
		if (cpf!=undefined) {
	        cpf = cpf.replace(/[^\d]+/g,'');
	        
	        if(cpf == '' || cpf.length != 11) return false;
	        
	        var resto;
	        var soma = 0;
	        
	        if (cpf == "00000000000" || cpf == "11111111111" || cpf == "22222222222" || cpf == "33333333333" || cpf == "44444444444" || cpf == "55555555555" || cpf == "66666666666" || cpf == "77777777777" || cpf == "88888888888" || cpf == "99999999999" || cpf == "12345678909") return false;
	        
	        for (i=1; i<=9; i++) soma = soma + parseInt(cpf.substring(i-1, i)) * (11 - i);
	        resto = (soma * 10) % 11;
	        
	        if ((resto == 10) || (resto == 11))  resto = 0;
	        if (resto != parseInt(cpf.substring(9, 10)) ) return false;
	        
	        soma = 0;
	        for (i = 1; i <= 10; i++) soma = soma + parseInt(cpf.substring(i-1, i)) * (12 - i);
	        resto = (soma * 10) % 11;
	        
	        if ((resto == 10) || (resto == 11))  resto = 0;
	        if (resto != parseInt(cpf.substring(10, 11) ) ) return false;
	        return true;
	    } else {
	    	return false;
	    }
    }
	

    function verifyCNPJ(cnpj) {
    	if (cnpj!=undefined) {
	        cnpj = cnpj.replace(/[^\d]+/g,'');

	        if(cnpj == '' || cnpj.length != 14) return false;

	        if (cnpj == "00000000000000" || cnpj == "11111111111111" || cnpj == "22222222222222" || cnpj == "33333333333333" || cnpj == "44444444444444" || cnpj == "55555555555555" || cnpj == "66666666666666" || cnpj == "77777777777777" || cnpj == "88888888888888" || cnpj == "99999999999999") return false;

	        var tamanho = cnpj.length - 2
	        var numeros = cnpj.substring(0,tamanho);
	        var digitos = cnpj.substring(tamanho);
	        var soma = 0;
	        var pos = tamanho - 7;
	        
	        for (i = tamanho; i >= 1; i--) {
	          soma += numeros.charAt(tamanho - i) * pos--;
	          if (pos < 2)
	                pos = 9;
	        }
	        
	        var resultado = soma % 11 < 2 ? 0 : 11 - soma % 11;
	        
	        if (resultado != digitos.charAt(0)) return false;

	        tamanho = tamanho + 1;
	        numeros = cnpj.substring(0,tamanho);
	        soma = 0;
	        pos = tamanho - 7;
	        
	        for (i = tamanho; i >= 1; i--) {
	          soma += numeros.charAt(tamanho - i) * pos--;
	          if (pos < 2) pos = 9;
	        }
	        
	        resultado = soma % 11 < 2 ? 0 : 11 - soma % 11;
	        
	        if (resultado != digitos.charAt(1)) return false;

	        return true; 
        } else {
	    	return false;
	    }
    }

    var customer_data_juridical = "<?php echo $this->customer_data_juridical; ?>";
    var customer_data_name = "<?php echo $this->customer_data_name; ?>";
    var customer_data_document = "<?php echo $this->customer_data_document; ?>";
    var customer_data_email = "<?php echo $this->customer_data_email; ?>";
    var customer_data_phone_number = "<?php echo $this->customer_data_phone_number; ?>";

    if (customer_data_email=="") {
    	if (document.getElementById('billing:email')) {
    		customer_data_email = document.getElementById('billing:email').value;
    	}
    }

    if (customer_data_phone_number=="") {
    	if (document.getElementById('billing:telephone')) {
    		customer_data_phone_number = document.getElementById('billing:telephone').value;
    	}
    }

	if (document.getElementById('gerencianet_billet_data_cnpj')) {
		if (customer_data_name!="" && customer_data_juridical) { 
			document.getElementById('gerencianet_billet_data_cnpj').value = customer_data_document;
		} else if (document.getElementsByName('billing[taxvat]')) {
			if (verifyCNPJ(document.getElementsByName('billing[taxvat]').value)) {
				document.getElementById('gerencianet_billet_data_cnpj').value = document.getElementsByName('billing[taxvat]').value;
			}
		}
	}
	if (document.getElementById('gerencianet_billet_data_corporate_name')) {
		if (customer_data_document!="" && customer_data_juridical) {
			document.getElementById('gerencianet_billet_data_corporate_name').value = customer_data_name;
		}
	}
	if (document.getElementById('gerencianet_billet_data_name')) {
		if (customer_data_name!="" && !customer_data_juridical) {
			document.getElementById('gerencianet_billet_data_name').value = customer_data_name;
		}
	}
	if (document.getElementById('gerencianet_billet_data_cpf')) {
		if (customer_data_document!="" && !customer_data_juridical) {
			document.getElementById('gerencianet_billet_data_cpf').value = customer_data_document;
		}
	}
	if (document.getElementById('gerencianet_billet_data_email')) {
		if (customer_data_email!="") {
			document.getElementById('gerencianet_billet_data_email').value = customer_data_email;
		}
	}
	if (document.getElementById('gerencianet_billet_data_phone_number')) {
		if (customer_data_phone_number!="") {
			document.getElementById('gerencianet_billet_data_phone_number').value = customer_data_phone_number;
		}
	}



    if (document.getElementById('billing:firstname')) {
		jQuery("[name='billing[firstname]']").change(function() {
			if (document.getElementById('billing:lastname')) {
				var full_name = this.value + " " + document.getElementById('billing:lastname').value;
			} else {
				var full_name = this.value;
			}
			
			jQuery('#gerencianet_billet_data_name').val(full_name);
			if (validateName(full_name)) {
				jQuery('#gerencianet_billet_data_name').removeClass("gn-inputs-error required-entry");
				jQuery('#gerencianet_billet_name_row').hide();
	        } else {
	            jQuery('#gerencianet_billet_data_name').addClass("gn-inputs-error required-entry");
	            jQuery('#gerencianet_billet_name_row').show();
			}

			if (document.getElementById('billing:taxvat') && verifyCNPJ(document.getElementById('billing:taxvat').value)) {
				jQuery('#gerencianet_billet_data_name').val("");
				if (document.getElementById('billing:firstname'))
					jQuery('#gerencianet_billet_data_corporate_name').val(document.getElementById('billing:firstname').value);
				jQuery('#gerencianet_billet_name_row').show();
			}
		});
	} else {
		jQuery('#gerencianet_billet_data_name').addClass("required-entry");
	}

	if (document.getElementById('billing:lastname')) {
		jQuery("[name='billing[lastname]']").change(function() {
			if (document.getElementById('billing:firstname')) {
				var full_name = document.getElementById('billing:firstname').value + " " + this.value;
			} else {
				var full_name = this.value;
			}
			
			jQuery('#gerencianet_billet_data_name').val(full_name);
			
			if (validateName(full_name)) {
				jQuery('#gerencianet_billet_data_name').removeClass("gn-inputs-error required-entry");
				jQuery('#gerencianet_billet_name_row').hide();
	        } else {
	            jQuery('#gerencianet_billet_data_name').addClass("gn-inputs-error required-entry");
	            jQuery('#gerencianet_billet_name_row').show();
			}

			if (document.getElementById('billing:taxvat') && verifyCNPJ(document.getElementById('billing:taxvat').value)) {
				jQuery('#gerencianet_billet_data_name').val("");
				if (document.getElementById('billing:firstname'))
					jQuery('#gerencianet_billet_data_corporate_name').val(document.getElementById('billing:firstname').value);
				jQuery('#gerencianet_billet_name_row').show();
			}
		});
	} else {
		jQuery('#gerencianet_billet_data_name').addClass("required-entry");
	}

	if (document.getElementById('billing:email')) {
		jQuery("[name='billing[email]']").change(function() {
			jQuery('#gerencianet_billet_data_email').val(this.value);
			if (validateEmail(this.value)) {
				jQuery('#gerencianet_billet_data_email').removeClass("gn-inputs-error required-entry");
	            jQuery('#gerencianet_billet_email_row').hide();
	        } else {
	            jQuery('#gerencianet_billet_data_email').addClass("gn-inputs-error required-entry");
	            jQuery('#gerencianet_billet_email_row').show();
			}
		});
	} else {
		jQuery('#gerencianet_billet_data_email').addClass("required-entry");
	}

	if (document.getElementsByName('billing[telephone]')) {
		jQuery("[name='billing[telephone]']").change(function() {
			jQuery('#gerencianet_billet_data_phone_number').val(this.value);
			if (validatePhone(this.value)) {
				jQuery('#gerencianet_billet_data_phone_number').removeClass("gn-inputs-error required-entry");
				if (verifyCPF(jQuery('#gerencianet_billet_data_cpf').val())) {
					jQuery('#gerencianet_billet_cpf_phone_row').hide();
				}
	        } else {
	            jQuery('#gerencianet_billet_data_phone_number').addClass("gn-inputs-error required-entry");
	            jQuery('#gerencianet_billet_cpf_phone_row').show();
			}
		});
	} else {
		jQuery('#gerencianet_billet_data_phone_number').addClass("required-entry");
	}

	if (document.getElementById('billing:taxvat')) {
		jQuery("[name='billing[taxvat]']").change(function() {
			if (verifyCPF(this.value)) {
				jQuery('#gerencianet_billet_data_cpf').val(this.value);
				jQuery('#gerencianet_billet_data_cpf').removeClass("gn-inputs-error required-entry");
				if (validatePhone(jQuery('#gerencianet_billet_data_phone_number').val())) {
					jQuery('#gerencianet_billet_cpf_phone_row').hide();
				}
				jQuery('#gerencianet_billet_juridical_data').addClass("gn-hide");
				jQuery('#gerencianet_billet_data_pay_card_as_juridical').prop( "checked", false );
			} else if (verifyCNPJ(this.value)) {
				jQuery('#gerencianet_billet_data_cnpj').val(this.value);
				jQuery('#gerencianet_billet_data_cnpj').removeClass("gn-inputs-error required-entry");
				jQuery('#gerencianet_billet_juridical_data').removeClass("gn-hide");
				jQuery('#gerencianet_billet_data_pay_card_as_juridical').prop( "checked", true );
			} else {
				jQuery('#gerencianet_billet_data_cpf').addClass("gn-inputs-error required-entry");
				jQuery('#gerencianet_billet_cpf_phone_row').show();
			}
		});
	} else {
		jQuery('#gerencianet_billet_data_cpf').addClass("required-entry");
	}
	
</script>