<?php
/**
 * Gerencianet
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Payment
 * @package    Gerencianet_Transparent
 * @copyright  Copyright (c) 2015 Gerencianet (http://www.gerencianet.com.br)
 * @author     AV5 Tecnologia <anderson@av5.com.br>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_code = $this->getMethodCode();
$isSandbox = Mage::helper('gerencianet_transparent')->isSandbox();
?>
<ul class="form-list" id="payment_form_<?php echo $_code ?>" style="display:none;">
	<?php if ($isSandbox):	?>
	<div class="alert-development">
		<strong>ATEN&Ccedil;&Atilde;O!</strong>
		<p>Essa loja est&aacute; em Modo Desenvolvimento. O pagamento de boleto ser&aacute; confirmado automaticamente no ambiente de Sandbox da Gerencianet.</p>
	</div>
	<?php endif; ?>
	<li class="first">
        O boleto estar&aacute; dispon&iacute;vel para impress&atilde;o ap&oacute;s a finaliza&ccedil;&atilde;o do pedido.
    </li>
</ul>
<style type="text/css">
.alert-development { color: #c90000; border: 1px solid #c90000; margin-top: 20px; margin-bottom: 20px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.alert-development p { color: #707070; margin: 0; padding: 0; font-size: 13px; }
</style>