<?php
/**
 * Gerencianet
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL).
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Payment
 * @package    Gerencianet_Transparent
 * @copyright  Copyright (c) 2015 Gerencianet (http://www.gerencianet.com.br)
 * @author     AV5 Tecnologia <anderson@av5.com.br>
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

$_code = $this->getMethodCode();
$isSandbox = Mage::helper('gerencianet_transparent')->isSandbox();
?>


<ul class="form-list billet-payment" id="payment_form_<?php echo $_code ?>" style="display:none;"><!-- v0.1.8.2 -->

	<script>
	if (document.getElementById('gerencianet_billet_data_name')) {
		<?php if ($this->customer_data_name!="") { ?>
			document.getElementById('gerencianet_billet_data_name').value = "<?php echo $this->customer_data_name; ?>";
		<?php } ?>
	}
	if (document.getElementById('gerencianet_billet_data_cpf')) {
		<?php if ($this->customer_data_document!="") { ?>
			document.getElementById('gerencianet_billet_data_cpf').value = "<?php echo $this->customer_data_document; ?>";
		<?php } ?>
	}
	if (document.getElementById('gerencianet_billet_data_email')) {
		<?php if ($this->customer_data_email!="") { ?>
			document.getElementById('gerencianet_billet_data_email').value = "<?php echo $this->customer_data_email; ?>";
		<?php } ?>
	}
	if (document.getElementById('gerencianet_billet_data_phone_number')) {
		<?php if ($this->customer_data_phone_number!="") { ?>
			document.getElementById('gerencianet_billet_data_phone_number').value = "<?php echo $this->customer_data_phone_number; ?>";
		<?php } ?>
	}

	</script>
	<?php if ($isSandbox):	?>
	<div class="alert-development">
		<strong>ATENÇÃO!</strong>
		<p>Essa loja está em Modo Desenvolvimento. Um boleto de teste será gerado no ambiente de Sandbox da Gerencianet.</p>
	</div>
	<?php endif; ?>

	<li class="first" style="text-align: left;">
        O boleto estará disponível para impressão após a finalização do pedido.
    </li>

    <div class="pay-juridical-person">
		<p><input type="checkbox" onchange="GerencianetTransparent.payBilletAsJuridical(this)" id="<?php echo $_code ?>_data_pay_billet_as_juridical" name="payment[data_pay_billet_as_juridical]" value="1" <?php if ($this->customer_data_juridical) { echo 'checked'; } ?> /> Pagar como Pessoa Jurídica.</p>
		<div id="<?php echo $_code ?>_juridical_data" <?php if (!$this->customer_data_juridical) { echo 'class="gn-hide"'; } ?>>

		<li>
		<label for="<?php echo $_code ?>_data_cnpj" class="required"><em>*</em><?php echo $this->__('CNPJ') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_data_cnpj" name="payment[data_cnpj]" title="<?php echo $this->__('CNPJ') ?>" class="input-text validate-number validate-length" value="<?php if ($this->customer_data_juridical) { echo $this->customer_data_document; } ?>" maxlength="14" />
		</div>
		</li>

		<li>
		<label for="<?php echo $_code ?>_data_corporate_name" class="required"><em>*</em><?php echo $this->__('Razão Social') ?></label>
			<div class="input-box">
				<input type="text" id="<?php echo $_code ?>_data_corporate_name" name="payment[data_corporate_name]" title="<?php echo $this->__('Razão Social') ?>" class="input-text" value="<?php if ($this->customer_data_juridical) { echo $this->customer_data_name; } ?>" maxlength="255" />
			</div>
		</li>
		</div>
	</div>

    <li <?php if (trim($this->customer_data_name) != "" && !$this->customer_data_juridical) { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_data_name" class="required"><em>*</em><?php echo $this->__('Nome') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_data_name" name="payment[data_name]" title="<?php echo $this->__('Name') ?>" class="input-text " value="" maxlength="255" />
		</div>
	</li>
    <li <?php if (trim($this->customer_data_document) != "" && !$this->customer_data_juridical) { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_data_cpf" class="required"><em>*</em><?php echo $this->__('CPF') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_data_cpf" name="payment[data_cpf]" class="input-text " title="<?php echo $this->__('CPF') ?>" value="" maxlength="11" />
		</div>
	</li>
    <li <?php if (trim($this->customer_data_email) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_data_email" class="required"><em>*</em><?php echo $this->__('Email') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_data_email" name="payment[data_email]" class="input-text " title="<?php echo $this->__('E-mail') ?>" value="" maxlength="255" />
		</div>
	</li>
    <li <?php if (trim($this->customer_data_phone_number) != "") { echo ' class="gn-hide"';} ?>>
		<label for="<?php echo $_code ?>_data_phone_number" class="required"><em>*</em><?php echo $this->__('Telefone (XX)XXXX-XXXX') ?></label>
		<div class="input-box">
			<input type="text" id="<?php echo $_code ?>_data_phone_number" name="payment[data_phone_number]" class="input-text " title="<?php echo $this->__('Phone Number') ?>" value="" maxlength="18" />
		</div>
	</li>
</ul>
<style type="text/css">
.gn-hide { display: none; }
.pay-juridical-person { color: #707070; border: 1px solid #CCC; margin-top: 20px; margin-bottom: 20px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.pay-juridical-person p { color: #707070; margin: 0; padding: 0; font-size: 13px; }
.alert-development { color: #c90000; border: 1px solid #c90000; margin-top: 20px; margin-bottom: 20px; padding: 10px; -webkit-border-radius: 3px; -moz-border-radius: 3px; border-radius: 3px; }
.alert-development p { color: #707070; margin: 0; padding: 0; font-size: 13px; }
</style>